language: node_js
node_js:
  - "4.2"
  - "4.1"
  - "4.0"
script:
  - npm run production
  - npm install --global mocha
  - npm run test
after_success:
  - npm install --global surge
  - npm run deploy
cache:
  directories:
    - node_modules
