language: node_js
node_js:
  - "4.2"
script:
  - npm run production
  - npm run test
after_success:
  - chmod +x deploy.sh
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
cache:
  directories:
    - node_modules
