language: node_js
node_js:
  - "4.2"
script:
  - bower install
  - npm run production
  - npm run test
  - npm run lint
after_success:
  - chmod +x deploy.sh
  - ./deploy.sh
cache:
  directories:
    - node_modules
