language: node_js
node_js:
  - "4.2"
script:
  - npm run production
  - npm install mocha
  - npm run test
after_success:
  - npm install surge
  - npm run deploy
cache:
  directories:
    - node_modules
