language: node_js
node_js:
  - "5.0"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
script:
  - npm run production
  - npm install -globall mocha
  - npm run test
cache:
  directories:
    - node_modules
